version: "3"

services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/
  redis:
    image: redis
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # smtp server
      - "8025:8025"  # ui
