version: "3"

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/
