# Generated by Django 3.0.8 on 2020-07-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='modified_date',
        ),
    ]
