# Generated by Django 3.0.8 on 2020-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Wydarzenie ciągłe',
                'verbose_name_plural': 'Wydarzenia ciągłe',
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Data wydarzenia',
            },
        ),
    ]
