# Generated by Django 3.0.8 on 2020-07-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventdate',
            options={},
        ),
        migrations.AddField(
            model_name='eventdate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.Event'),
            preserve_default=False,
        ),
    ]
