# Generated by Django 3.0.8 on 2020-07-14 16:32
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
