# Generated by Django 3.0.8 on 2020-07-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_index_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_field',
            field=models.TextField(blank=True),
        ),
    ]
