# Generated by Django 3.0.8 on 2020-07-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200712_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='modified_date',
        ),
    ]
